#pragma once

#include <cstdint>

// ============================================================
// Hand-drawn 48x48 code-native sprite (no image decoder needed).
// Theme: pink hair, fair skin, red lips, black choker, burgundy velvet deep-V.
// Keeps the original signature, so callers need no change.
// Generated by portrait_builder.py -- edit the builder, not this file.
// All frame arithmetic is explicitly int-cast for -Wall -Wextra -Werror.
// ============================================================

enum class PortraitState {
    Idle, Listening, Thinking, Speaking, Sad, Sleepy, Wake
};

// Palette and helpers live in a dedicated namespace: no global pollution, and
// every constant is referenced by the helpers (avoids -Wunused-variable).
namespace folo_portrait {

constexpr uint32_t hair_dark = 0x8A4560, hair = 0xC86E8F, hair_light = 0xE894AD, skin = 0xFFD9C8, skin_shade = 0xE8B49E, blush = 0xF08FA5, lip = 0xC03050, lip_light = 0xD84060, cloth = 0x7A1E35, cloth_seam = 0x5A1428, choker = 0x1A1A22, ink = 0x241C26, white = 0xFFF8F6, tear = 0x8FC8E8;

template <typename R> inline void FoloBase(R r) {
    r(17, 2, 15, 2, hair_dark); r(12, 4, 24, 2, hair_dark); r(9, 6, 29, 3, hair_dark);
    r(7, 9, 33, 9, hair_dark); r(6, 18, 35, 17, hair_dark); r(4, 32, 39, 9, hair_dark);
    r(3, 40, 41, 4, hair_dark); r(16, 4, 16, 2, hair); r(12, 6, 23, 3, hair); r(9, 9, 29, 17, hair);
    r(8, 23, 31, 12, hair); r(6, 34, 35, 7, hair); r(5, 40, 37, 2, hair); r(12, 8, 3, 4, hair_light);
    r(10, 12, 2, 12, hair_light); r(8, 27, 2, 9, hair_light); r(6, 37, 2, 3, hair_light);
    r(30, 7, 4, 2, hair_light); r(34, 10, 2, 5, hair_light); r(37, 23, 2, 11, hair_light);
    r(39, 36, 2, 4, hair_light); r(12, 19, 3, 7, skin_shade); r(34, 19, 3, 7, skin_shade);
    r(14, 12, 20, 16, skin_shade); r(16, 27, 16, 4, skin_shade); r(19, 31, 10, 2, skin_shade);
    r(15, 12, 18, 14, skin); r(16, 25, 16, 4, skin); r(19, 29, 11, 2, skin); r(14, 9, 13, 6, hair);
    r(13, 13, 10, 4, hair); r(13, 17, 7, 2, hair); r(13, 19, 4, 2, hair); r(23, 9, 4, 4, hair);
    r(26, 10, 3, 3, hair); r(29, 11, 3, 5, hair); r(32, 13, 3, 6, hair); r(16, 10, 2, 5, hair_light);
    r(20, 9, 2, 4, hair_light); r(16, 18, 6, 1, hair_dark); r(22, 17, 2, 1, hair_dark);
    r(27, 18, 6, 1, hair_dark); r(25, 17, 2, 1, hair_dark); r(24, 26, 1, 1, skin_shade);
    r(14, 26, 4, 2, blush); r(30, 26, 4, 2, blush); r(20, 31, 9, 7, skin_shade); r(21, 31, 7, 6, skin);
    r(19, 34, 11, 2, choker); r(23, 34, 3, 2, lip); r(24, 34, 1, 1, white); r(14, 36, 21, 2, hair_dark);
    r(10, 38, 29, 3, hair_dark); r(8, 41, 33, 6, hair_dark); r(14, 37, 20, 3, cloth);
    r(11, 40, 27, 2, cloth); r(9, 42, 31, 5, cloth); r(21, 36, 7, 2, skin); r(22, 38, 5, 2, skin_shade);
    r(14, 43, 2, 4, cloth_seam); r(34, 43, 2, 4, cloth_seam); r(19, 44, 11, 1, cloth_seam);
}

template <typename R> inline void FoloEyesOpen(R r) {
    r(16, 21, 6, 1, ink); r(27, 21, 6, 1, ink); r(17, 22, 4, 2, white); r(28, 22, 4, 2, white);
    r(18, 22, 2, 2, ink); r(29, 22, 2, 2, ink); r(16, 20, 2, 1, ink); r(15, 19, 1, 1, ink);
    r(31, 20, 2, 1, ink); r(32, 19, 1, 1, ink); r(17, 24, 4, 1, skin_shade); r(28, 24, 4, 1, skin_shade);
}

template <typename R> inline void FoloEyesClosed(R r) {
    r(16, 22, 6, 1, ink); r(27, 22, 6, 1, ink); r(17, 23, 4, 1, hair_dark); r(28, 23, 4, 1, hair_dark);
}

template <typename R> inline void FoloEyesWide(R r) {
    r(16, 20, 6, 1, ink); r(27, 20, 6, 1, ink); r(17, 21, 4, 3, white); r(28, 21, 4, 3, white);
    r(18, 21, 2, 3, ink); r(29, 21, 2, 3, ink);
}

template <typename R> inline void FoloEyesSquint(R r) {
    r(16, 22, 6, 1, ink); r(27, 22, 6, 1, ink); r(17, 23, 4, 1, white); r(28, 23, 4, 1, white);
    r(19, 23, 1, 1, ink); r(30, 23, 1, 1, ink);
}

template <typename R> inline void FoloEyesSad(R r) {
    r(16, 21, 6, 1, ink); r(27, 21, 6, 1, ink); r(17, 22, 4, 2, white); r(28, 22, 4, 2, white);
    r(18, 23, 2, 1, ink); r(29, 23, 2, 1, ink); r(15, 22, 2, 1, ink); r(32, 22, 2, 1, ink);
}

template <typename R> inline void FoloMouthNeutral(R r) {
    r(21, 28, 7, 1, lip); r(22, 29, 5, 1, lip_light); r(24, 29, 1, 1, white);
}

template <typename R> inline void FoloMouthOpen(R r) {
    r(21, 28, 7, 2, lip); r(22, 29, 5, 2, cloth_seam); r(22, 30, 5, 1, lip_light);
}

template <typename R> inline void FoloMouthSmile(R r) {
    r(21, 28, 7, 1, lip); r(22, 29, 5, 1, lip_light); r(23, 28, 3, 1, white);
}

template <typename R> inline void FoloMouthSad(R r) {
    r(22, 29, 5, 1, lip); r(21, 28, 1, 1, lip); r(29, 28, 1, 1, lip);
}

}  // namespace folo_portrait

template <typename Rect>
void DrawPixelPortrait(Rect rect, PortraitState state, unsigned frame) {
    auto r = [&](int x, int y, int w, int h, uint32_t c) {
        rect(x, y, w, h, c);
    };
    using namespace folo_portrait;
    FoloBase(r);
    switch (state) {
        case PortraitState::Idle: {
            if (frame % 16u == 15u) FoloEyesClosed(r);
            else FoloEyesOpen(r);
            FoloMouthNeutral(r);
        if (frame % 8u < 4u) { r(4, 12, 2, 2, lip); r(6, 12, 2, 2, lip);
            r(5, 14, 3, 1, lip); }
            break;
        }
        case PortraitState::Listening: {
            FoloEyesSquint(r);
            FoloMouthNeutral(r);
        for (int i = 0; i < 3; ++i) {
            int h = 2 + int((frame + i) % 3) * 2;
            r(i * 2, 23 - h / 2, 1, h, hair_light);
            r(45 - i * 2, 23 - h / 2, 1, h, hair_light);
        }
            break;
        }
        case PortraitState::Thinking: {
            FoloEyesSquint(r);
            FoloMouthNeutral(r);
        r(25, 30, 4, 7, skin_shade); r(24, 29, 2, 3, skin);
        r(26, 34, 4, 7, skin_shade); r(28, 35, 2, 2, skin_shade);
        for (int i = 0; i < 3; ++i) {
            r(36 + i * 4, 5, 2, 2, i <= int(frame % 3) ? lip : cloth_seam);
        }
            break;
        }
        case PortraitState::Speaking: {
            if (frame % 16u == 15u) FoloEyesClosed(r);
            else FoloEyesOpen(r);
            if (frame % 2u == 0u) FoloMouthOpen(r);
            else FoloMouthNeutral(r);
        r(37, 32, 4, 9, skin_shade); r(38, 29, 5, 7, skin);
        r(37, 27, 1, 5, skin); r(39, 25, 1, 5, skin); r(41, 25, 1, 5, skin);
        r(43, 27, 1, 6, skin); r(35, 31, 3, 2, skin);
            break;
        }
        case PortraitState::Sad: {
            FoloEyesSad(r);
            FoloMouthSad(r);
        r(25, 25, 1, 3, tear); r(33, 26, 1, 2, tear);
            break;
        }
        case PortraitState::Sleepy: {
            FoloEyesClosed(r);
            FoloMouthNeutral(r);
        { int s = int(frame % 3);
          r(37, 6 + s, 4, 1, white); r(39, 8 + s, 2, 1, white);
          r(37, 10 + s, 4, 1, white); r(35, 13 + s, 3, 1, white);
          r(39, 13 + s, 2, 1, white); }
            break;
        }
        case PortraitState::Wake: {
            FoloEyesWide(r);
            FoloMouthSmile(r);
        r(4, 12, 2, 2, lip); r(7, 12, 2, 2, lip); r(4, 14, 5, 2, lip);
        r(41, 14, 2, 2, lip); r(44, 12, 2, 2, lip);
            break;
        }
        default: FoloEyesOpen(r); FoloMouthNeutral(r); break;
    }
}
